### ISSUE TITLE
PreTrain-T5-[get_samples_mapping]-[ RuntimeError: Socket Timeout ]

### ISSUE THREAD

**Issue by Hanlard** [NVIDIA/Megatron-LM#109]
In the megatron\data\dataset_utils.py "get_samples_mapping" function,  the following line had run for 12 hours.        
 samples_mapping = helpers.build_mapping(..)
 
And this line only runs for rank=0, so the next line torch.distributed.all_reduce(counts, ... ) reports [ RuntimeError: Socket Timeout ]

**Comment by Hanlard** [comment]
## This is all log
using world size: 2, data-parallel-size: 2, tensor-model-parallel size: 1, pipeline-model-parallel size: 1
WARNING: overriding default arguments for tokenizer_type:BertWordPieceLowerCase with tokenizer_type:JIEBATokenizer
using torch.float16 for parameters ...
------------------------ arguments ------------------------
accumulate_allreduce_grads_in_fp32 .............. False
adam_beta1 ...................................... 0.9
adam_beta2 ...................................... 0.999
adam_eps ........................................ 1e-08
adlr_autoresume ................................. False
adlr_autoresume_interval ........................ 1000
apply_query_key_layer_scaling ................... True
apply_residual_connection_post_layernorm ........ False
attention_dropout ............................... 0.1
attention_softmax_in_fp32 ....................... False
balance_loss_weight ............................. 1
balance_strategy ................................ switch
bert_binary_head ................................ True
bert_load ....................................... None
bf16 ............................................ False
bias_dropout_fusion ............................. True
bias_gelu_fusion ................................ True
biencoder_projection_dim ........................ 0
biencoder_shared_query_context_model ............ False
block_data_path ................................. None
checkpoint_activations .......................... False
checkpoint_num_layers ........................... 1
clip_grad ....................................... 1.0
consumed_train_samples .......................... 0
consumed_valid_samples .......................... 0
data_impl ....................................... mmap
data_parallel_size .............................. 2
data_path ....................................... ['/userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document']
dataloader_type ................................. single
DDP_impl ........................................ local
decoder_seq_length .............................. 128
distribute_checkpointed_activations ............. False
distributed_backend ............................. nccl
embedding_path .................................. None
encoder_seq_length .............................. 512
eod_mask_loss ................................... False
eval_interval ................................... 1000
eval_iters ...................................... 10
evidence_data_path .............................. None
exit_duration_in_mins ........................... None
exit_interval ................................... None
ffn_hidden_size ................................. 3072
finetune ........................................ False
fmoefy .......................................... True
fp16 ............................................ True
fp16_lm_cross_entropy ........................... False
fp32_residual_connection ........................ False
global_batch_size ............................... 32
hidden_dropout .................................. 0.1
hidden_hidden_size .............................. None
hidden_size ..................................... 768
hysteresis ...................................... 2
ict_head_size ................................... None
ict_load ........................................ None
img_dim ......................................... 224
indexer_batch_size .............................. 128
indexer_log_interval ............................ 1000
init_method_std ................................. 0.02
init_method_xavier_uniform ...................... False
initial_loss_scale .............................. 4294967296
kv_channels ..................................... 64
layernorm_epsilon ............................... 1e-05
lazy_mpu_init ................................... None
load ............................................ checkpoints/gpt_108M_testCB2
local_rank ...................................... 0
log_batch_size_to_tensorboard ................... False
log_interval .................................... 10
log_learning_rate_to_tensorboard ................ True
log_loss_scale_to_tensorboard ................... True
log_num_zeros_in_grad ........................... False
log_params_norm ................................. False
log_timers_to_tensorboard ....................... False
log_validation_ppl_to_tensorboard ............... False
loss_scale ...................................... None
loss_scale_window ............................... 1000
lr .............................................. 0.0001
lr_decay_iters .................................. 10000
lr_decay_samples ................................ None
lr_decay_style .................................. linear
lr_warmup_fraction .............................. 0.01
lr_warmup_iters ................................. 0
lr_warmup_samples ............................... 0
make_vocab_size_divisible_by .................... 128
mask_prob ....................................... 0.15
masked_softmax_fusion ........................... True
max_position_embeddings ......................... 512
merge_file ...................................... bpe_3w_new/chinese_vocab.model
micro_batch_size ................................ 4
min_loss_scale .................................. 1.0
min_lr .......................................... 1e-05
mmap_warmup ..................................... False
no_load_optim ................................... None
no_load_rng ..................................... None
no_save_optim ................................... None
no_save_rng ..................................... None
num_attention_heads ............................. 12
num_channels .................................... 3
num_classes ..................................... 1000
num_experts ..................................... 2
num_layers ...................................... 12
num_layers_per_virtual_pipeline_stage ........... None
num_workers ..................................... 2
onnx_safe ....................................... None
openai_gelu ..................................... False
optimizer ....................................... adam
override_lr_scheduler ........................... False
params_dtype .................................... torch.float16
patch_dim ....................................... 16
pipeline_model_parallel_size .................... 1
query_in_block_prob ............................. 0.1
rampup_batch_size ............................... None
rank ............................................ 0
reset_attention_mask ............................ False
reset_position_ids .............................. False
retriever_report_topk_accuracies ................ []
retriever_score_scaling ......................... False
retriever_seq_length ............................ 256
sample_rate ..................................... 1.0
save ............................................ checkpoints/gpt_108M_testCB2
save_interval ................................... 10000
scatter_gather_tensors_in_pipeline .............. True
seed ............................................ 1234
seq_length ...................................... 512
sgd_momentum .................................... 0.9
short_seq_prob .................................. 0.1
split ........................................... 949,50,1
tensor_model_parallel_size ...................... 1
tensorboard_dir ................................. None
tensorboard_log_interval ........................ 1
tensorboard_queue_size .......................... 1000
titles_data_path ................................ None
tokenizer_type .................................. JIEBATokenizer
top_k ........................................... 1
train_iters ..................................... 10000
train_samples ................................... None
use_checkpoint_lr_scheduler ..................... False
use_contiguous_buffers_in_ddp ................... False
use_cpu_initialization .......................... None
use_one_sent_docs ............................... False
virtual_pipeline_model_parallel_size ............ None
vocab_extra_ids ................................. 0
vocab_file ...................................... bpe_3w_new/vocab.json
weight_decay .................................... 0.01
world_size ...................................... 2
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 4
> building JIEBATokenizer tokenizer ...
> padded vocab (size: 30001) with 79 dummy tokens (new size: 30080)
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
> compiling dataset index builder ...
make: Entering directory '/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data'
make: Nothing to be done for 'default'.
make: Leaving directory '/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data'
>>> done with dataset index builder. Compilation time: 0.155 seconds
> compiling and loading fused kernels ...
Detected CUDA files, patching ldflags
Emitting ninja build file /userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_upper_triang_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_upper_triang_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/fused_kernels/build/build.ninja...
Building extension module scaled_masked_softmax_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module scaled_masked_softmax_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/fused_kernels/build/build.ninja...
Building extension module fused_mix_prec_layer_norm_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_mix_prec_layer_norm_cuda...
>>> done with compiling and loading fused kernels. Compilation time: 1.838 seconds
time to initialize megatron (seconds): -7.176
[after megatron is initialized] datetime: 2021-06-08 21:32:40
building T5 model ...
> number of parameters on (tensor, pipeline) model parallel rank (0, 0): 222003584
> learning rate decay style: linear
WARNING: could not find the metadata file checkpoints/gpt_108M_testCB2/latest_checkpointed_iteration.txt
will not load any checkpoints and will start from random
time (ms) | load-checkpoint: 0.33
[after model, optimizer, and learning rate scheduler are built] datetime: 2021-06-08 21:32:40
> building train, validation, and test datasets ...
> datasets target sizes (minimum size):
train: 320000
validation: 3520
test: 320
> building train, validation, and test datasets for T5 ...
> building dataset index ...
reading sizes...
reading pointers...
reading document index...
creating numpy buffer of mmap...
creating memory view of numpy buffer...
> finished creating indexed dataset in 0.052948 seconds
> indexed dataset stats:
number of documents: 668
number of sentences: 106807670
> dataset split:
train:
document indices in [0, 634) total of 634 documents
sentence indices in [0, 101821893) total of 101821893 sentences
validation:
document indices in [634, 667) total of 33 documents
sentence indices in [101821893, 106771945) total of 4950052 sentences
test:
document indices in [667, 668) total of 1 documents
sentence indices in [106771945, 106807670) total of 35725 sentences
> WARNING: could not find index map file /userhome/gpt3_data_train/cpm_ReTrain_addBaiKe_100G/Data_Processed_text_document_train_indexmap_320000mns_510msl_0.10ssp_1234s.npy, building the indices on rank 0 ...
> building sapmles index mapping for train ...
using uint32 for data mapping...
using:
number of documents: 634
sentences range: [0, 101821893)
total number of sentences: 101821893
number of epochs: 2147483646
maximum number of samples: 320000
maximum sequence length: 510
short sequence probability: 0.1
short sequence ration (1/prob): 10
seed: 1234
Traceback (most recent call last):
File "pretrain_t5.py", line 133, in <module>
pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/training.py", line 131, in pretrain
= build_train_valid_test_data_iterators(
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/training.py", line 815, in build_train_valid_test_data_iterators
train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
File "pretrain_t5.py", line 114, in train_valid_test_datasets_provider
train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data/dataset_utils.py", line 425, in build_train_valid_test_datasets
return _build_train_valid_test_datasets(data_prefix[0],
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data/dataset_utils.py", line 578, in _build_train_valid_test_datasets
train_dataset = build_dataset(0, 'train')
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data/dataset_utils.py", line 552, in build_dataset
dataset = T5Dataset(
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data/t5_dataset.py", line 47, in __init__
self.samples_mapping = get_samples_mapping(self.indexed_dataset,
File "/userhome/megatron/megatron_t5_moe/Megatron-LM-T5moe/megatron/data/dataset_utils.py", line 703, in get_samples_mapping
torch.distributed.all_reduce(counts, group=mpu.get_data_parallel_group())
File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
work = group.allreduce([tensor], opts)
RuntimeError: Socket Timeout

**Comment by Hanlard** [comment]
## This is relative code:
        from megatron.data import helpers
        [Always Running in rank=0] -> samples_mapping = helpers.build_mapping(
            indexed_dataset.doc_idx,
            indexed_dataset.sizes,
            num_epochs,
            max_num_samples,
            max_seq_length,
            short_seq_prob,
            seed,
            verbose,
            2 if binary_head else 1)
        print_rank_0(' > done building sapmles index maping')
        np.save(indexmap_filename, samples_mapping, allow_pickle=True)
        print_rank_0(' > saved the index mapping in {}'.format(
            indexmap_filename))
        # Make sure all the ranks have built the mapping
        print_rank_0(' > elasped time to build and save samples mapping '
                     '(seconds): {:4f}'.format(
                         time.time() - start_time))
    # This should be a barrier but nccl barrier assumes
    # device_index=rank which is not the case for model
    # parallel case
    counts = torch.cuda.LongTensor([1])
    [Report Timeout ERROR] -> torch.distributed.all_reduce(counts, group=mpu.get_data_parallel_group())
    torch.distributed.all_reduce(counts, group=mpu.get_pipeline_model_parallel_group())

**Comment by bugface** [comment]
I had a similar issue when using DDP and model parallel.
I solved the issue as
set timeout to a longer time (default is 30min) in the torch.distributed.init_process_group (megatron/initialize.py at line 183)
```
torch.distributed.init_process_group( 
  backend=args.distributed_backend, 
  timeout=datetime.timedelta(0, 3600),  ## notice here I change the timeout to 2 hours 
  world_size=args.world_size, 
  rank=args.rank, 
  init_method=init_method 
)
```
