### ISSUE TITLE
[BUG] Problem in Text generation with Mixtral 8x7B

### ISSUE THREAD

**Issue by paprika0741** [NVIDIA/Megatron-LM#1576]
**Describe the bug**
[run.log](https://github.com/user-attachments/files/20204314/run.log)
I am unable to successfully run tools/run_text_generation_server.py using the configuration:
--pipeline-model-parallel-size=4
--tensor-model-parallel-size=1
--expert-model-parallel-size=1
It appears that  rank 1, rank 2, and rank 3 exit unexpectedly shortly after engine initialization.

```
rank 0] Start running engine.
[rank 0] Run server.
 * Serving Flask app 'megatron.inference.text_generation_server'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.31.39.99:5000
INFO:werkzeug:Press CTRL+C to quit
[rank 3] Start running engine.
[rank 2] Start running engine.
[rank 1] Start running engine.
[rank3]:[W514 09:04:56.764937624 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank2]:[W514 09:04:56.818801359 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank1]:[W514 09:04:56.846942447 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
ip-172-31-39-99:88202:89261 [1] NCCL INFO [Service thread] Connection closed by localRank 1
ip-172-31-39-99:88204:89260 [3] NCCL INFO [Service thread] Connection closed by localRank 3
ip-172-31-39-99:88203:89259 [2] NCCL INFO [Service thread] Connection closed by localRank 2
ip-172-31-39-99:88203:89264 [2] NCCL INFO [Proxy Service UDS] exit: stop 1 abortFlag 1
ip-172-31-39-99:88204:89263 [3] NCCL INFO [Proxy Service UDS] exit: stop 1 abortFlag 1
ip-172-31-39-99:88202:89265 [1] NCCL INFO [Proxy Service UDS] exit: stop 1 abortFlag 1
ip-172-31-39-99:88202:90510 [1] NCCL INFO comm 0x48194800 rank 1 nranks 4 cudaDev 1 busId 1c0 - Abort COMPLETE
ip-172-31-39-99:88204:90511 [3] NCCL INFO comm 0x48acdb00 rank 3 nranks 4 cudaDev 3 busId 1e0 - Abort COMPLETE
ip-172-31-39-99:88203:90512 [2] NCCL INFO comm 0x1d9610b0 rank 2 nranks 4 cudaDev 2 busId 1d0 - Abort COMPLETE
request IP: 127.0.0.1
{"prompts": ["hi"], "tokens_to_generate": 1}
start time:  2025-05-14 09:07:01.998523
ERROR:megatron.inference.text_generation_server:Exception on /api [PUT]
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/CodeSpace/Megatron-LM/megatron/inference/text_generation_server.py", line 197, in put
    send_do_generate()  # Tell other ranks we're doing generate
    ^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/CodeSpace/Megatron-LM/megatron/inference/endpoints/common.py", line 13, in send_do_generate
    torch.distributed.broadcast(choice, 0)
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/mg-llm/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 2417, in broadcast
    work = default_pg.broadcast([tensor], opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: ProcessGroupWrapper: Monitored Barrier encountered error running collective: CollectiveFingerPrint(SequenceNumber=5, OpType=BROADCAST, TensorShape=[1], TensorDtypes=Long, TensorDeviceTypes=TensorOptions(dtype=float (default), device=cuda, layout=Strided (default), requires_grad=false (default), pinned_memory=false (default), memory_format=(nullopt))). Error: 
[../third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.31.39.99]:42186
INFO:werkzeug:127.0.0.1 - - [14/May/2025 09:07:02] "PUT /api HTTP/1.1" 500 -

```

Problem in 
**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.
```
#!/bin/bash
# This example will start serving the Mixtral 8x7B model.
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=ALL
export TORCH_DISTRIBUTED_DEBUG=DETAIL 
# export NCCL_ASYNC_ERROR_HANDLING=1
# export NCCL_IB_DISABLE=1
# export NCCL_SOCKET_IFNAME=ens5
# export CUDA_DEVICE_MAX_CONNECTIONS=1

DISTRIBUTED_ARGS="--nproc_per_node 4 \
                  --nnodes 1 \
                  --node_rank 0 \
                  --master_addr localhost \
                  --master_port 6000"

# CHECKPOINT=/home/ec2-user/CodeSpace/Megatron-LM/ckp/mixtral-mcore-TP1PP1EP1
# CHECKPOINT=/home/ec2-user/CodeSpace/Megatron-LM/ckp/mixtral-mcore-TP1PP2EP1
CHECKPOINT="/mnt/data/mixtral-mcore-TP1PP4EP1Layer16"
TOKENIZER_MODEL=/home/ec2-user/CodeSpace/Megatron-LM/ckp/tokenizer.model

export CUDA_DEVICE_MAX_CONNECTIONS=1
torchrun $DISTRIBUTED_ARGS ../tools/run_text_generation_server.py   \
       --port 5000 \
       --tensor-model-parallel-size 1  \
       --pipeline-model-parallel-size 4  \
       --expert-model-parallel-size 1 \
       --load ${CHECKPOINT}  \
       --tokenizer-type Llama2Tokenizer \
       --tokenizer-model $TOKENIZER_MODEL \
       --use-mcore-models \
       --max-position-embeddings 32768 \
       --num-layers 16 \
       --hidden-size 4096 \
       --ffn-hidden-size 14336 \
       --num-attention-heads 32 \
       --normalization RMSNorm \
       --disable-bias-linear \
       --position-embedding-type rope \
       --no-position-embedding \
       --swiglu \
       --untie-embeddings-and-output-weights \
       --group-query-attention \
       --num-query-groups 8 \
       --bf16  \
       --micro-batch-size 1  \
       --seq-length 1024  \
       --seed 42 \
       --num-experts 8 \
       --moe-router-topk 2 \
       --moe-token-dispatcher-type alltoall \
       --moe-grouped-gemm \
       --rotary-base 1000000 \
       --no-rope-fusion \
       --no-gradient-accumulation-fusion \
       --max-batch-size 1
       # --mock-data \
       # 

```
**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.

**Environment (please complete the following information):**
 - Megatron-LM commit ID： aa6207e2da6bca789375f591c9124aa408d2509a (HEAD, tag: v0.11.0, tag: core_v0.11.0)
 - PyTorch version: 2.5.1+cu124
 - CUDA version: 12.4
 - NCCL version: 2.21.5
 - GPUs: 4× NVIDIA A10G
 - OS: Amazon Linux 2023

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by paprika0741** [comment]
I solved it. It should be based on the latest code.

**Comment by hxq2333** [comment]
did you run it with --moe-grouped-gemm ? it seems mixtral8*7b is based on SequentialMLP?
