### ISSUE TITLE
[BUG] Checkpoint validation is broken, does not use any of Megatron's process groups.

### ISSUE THREAD

**Issue by Skylion007** [NVIDIA/Megatron-LM#1707]
**Describe the bug**
https://github.com/NVIDIA/Megatron-LM/blob/94bd476bd840c2fd4c3ebfc7448c2af220f4832b/megatron/core/dist_checkpointing/validation.py#L387 does not use process groups, (as does other objects in the process group file). When training on large number of nodes, it tries to reduce the state_dict via the default process group NCCL, which causes an OOM and CUDA failure. We should specify the correct process group here, but I am unsure about what the correct process group to use is here. Presumably this comparison is intended to be used via a GLOO process group to avoid this OOM behavior.

**To Reproduce**
Steps to reproduce the behavior. The easier it is to reproduce the faster it will get maintainer attention.

**Expected behavior**

**Stack trace/logs**
If applicable, add the stack trace or logs from the time of the error.

**Environment (please complete the following information):**
 - Megatron-LM commit ID
 - PyTorch version
 - CUDA version
 - NCCL version

**Proposed fix**
If you have a proposal for how to fix the issue state it here or link to a PR.

**Additional context**

**Comment by ananthsub** [comment]
The common state dict is intended to represent non-tensor states to be persisted in the checkpoint. This validation check is run in order to warn users if there is a difference across ranks, as only the common state dict from global rank 0 is saved and non-rank-zero common states are not persisted.

One optimization actively being worked on is to broadcast the common state dict from rank 0 in order to do the comparison. This would mean that each rank contains at most 2 common state dicts, the local one and the one from rank 0, which would reduce the peak memory usage. the broadcast would still use the global process group

**Comment by Skylion007** [comment]
So an alternative way to around this would be to edit the code to disable this check and then just reload the checkpoint in strict mode to verify that the checkpoint is valid?

**Comment by ananthsub** [comment]
to disable this check, yes you could edit the code to set `validate_sharding_integrity = False` here:

https://github.com/NVIDIA/Megatron-LM/blob/94bd476bd840c2fd4c3ebfc7448c2af220f4832b/megatron/training/checkpointing.py#L471-L495

note that this would disable the common state dict check as well as other checks on the sharded tensors/objects in the state dict: https://github.com/NVIDIA/Megatron-LM/blob/94bd476bd840c2fd4c3ebfc7448c2af220f4832b/megatron/core/dist_checkpointing/validation.py#L403-L438

at the moment unforuntately there's no way to toggle off only the common state dict check

**Comment by Skylion007** [comment]
Doing that gave me different OOM errors here with ASYNC checkpointing. Any tips to reduce GPU memory usage? I just want to move it to CPU for async saving, and it only OOMs when saving the checkpoint despite having 50+% free memory
```
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/async_utils.py", line 452, in async_loop
    async_fn_args[1] = item.preload_fn()
                       ^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/filesystem_async.py", line 229, in preload_tensors
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 1039, in synchronize
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 495, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/async_utils.py", line 452, in async_loop
    async_fn_args[1] = item.preload_fn()
                       ^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/filesystem_async.py", line 229, in preload_tensors
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 1039, in synchronize
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 495, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Process SpawnProcess-2:
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/async_utils.py", line 452, in async_loop
    async_fn_args[1] = item.preload_fn()
                       ^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/filesystem_async.py", line 229, in preload_tensors
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 1039, in synchronize
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 495, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/async_utils.py", line 452, in async_loop
    async_fn_args[1] = item.preload_fn()
                       ^^^^^^^^^^^^^^^^^
  File "/mnt/sharefs/users/runner/MoEva-Megatron-LLM/megatron/core/dist_checkpointing/strategies/filesystem_async.py", line 229, in preload_tensors
    torch.cuda.synchronize()
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 1039, in synchronize
    with torch.cuda.device(device):
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 495, in __enter__
    self.prev_idx = torch.cuda._exchange_device(self.idx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Skylion007** [comment]
Actually, the 2nd error seems I solved by enabling the expandable segmentable allocator. This reduced memory fragmentation enough for it to complete. 

@ananthsub For the PR to fix this properly. I presume you meant something like this?
```python
def _validate_common_state_dict(common_state_dict: CommonStateDict) -> None:
    """Validate consistency across ranks for the common state dict.

    Rank 0 broadcasts its common state dict. All ranks compare it with their local version
    and return any differences. Rank 0 logs all diffs across ranks.

    Args:
        common_state_dict: The common state dict present in all ranks.
    """
    rank = torch.distributed.get_rank()
    world_size = torch.distributed.get_world_size()

    # Broadcast the common state dict from rank 0
    reference_state_dict = common_state_dict if rank == 0 else None
    reference_state_dict = torch.distributed.broadcast_object_list([reference_state_dict], src=0)[0]

    # Compare each rank's state dict with the reference
    only_left, only_right, mismatch = diff(reference_state_dict, common_state_dict)

    # Prepare output tuple if there's a difference
    local_diff = (only_left, only_right, mismatch) if (only_left or only_right or mismatch) else None

    # Gather diffs from all ranks to rank 0
    all_diffs = [None] * world_size if rank == 0 else None
    torch.distributed.gather_object(local_diff, all_diffs, dst=0)

    if rank == 0:
        common_state_dict_diff = {
            r: diff_tuple for r, diff_tuple in enumerate(all_diffs) if diff_tuple is not None
        }

        if common_state_dict_diff:
            logger.warning(
                f"There is difference in the common state dict in different ranks. The differences are {common_state_dict_diff}"
            )
```

**Comment by Skylion007** [comment]
@ananthsub The fix works great for saving, but I am unfortunately having NCCL/deadlocks issues. It's freezing right after `Loading distributed optimizer sharded state of type fully_sharded_model_space`, I think it's running out of GPU memory. Is there anyway we can reduce the memory usage slightly for loading checkpoints? Saving works fine. I'm getting:
```[rank76]:[E728 18:33:18.660186597 ProcessGroupNCCL.cpp:1772] [PG ID 18 PG GUID 13008 Rank 76] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API (e.g., CudaEventDestroy) hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api (for example, CudaEventDestroy), or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang.
[rank76]:[E728 18:33:19.245204860 ProcessGroupNCCL.cpp:1772] [PG ID 0 PG GUID 0(default_pg) Rank 76] Received a dump signal due to a collective timeout from this local rank and we will try our best to dump the debug info. Last enqueued NCCL work: 45, last completed NCCL work: 45.This is most likely caused by incorrect usages of collectives, e.g., wrong sizes used across ranks, the order of collectives is not same for all ranks or the scheduled collective, for some reason, didn't run. Additionally, this can be caused by GIL deadlock or other reasons such as network errors or bugs in the communications library (e.g. NCCL), etc.
[rank76]:[E728 18:33:19.245526108 ProcessGroupNCCL.cpp:1562] [PG ID 0 PG GUID 0(default_pg) Rank 76] ProcessGroupNCCL preparing to dump debug info. Include stack trace: 1
```
I am guessing one of the workers is dying when running out of memory or otherwise deadlocking with NCCL, but not sure why. I did try to disable validating the checkpoint, I am not sure if that broke checkpoint loading

**Comment by Skylion007** [comment]
Closed by https://github.com/NVIDIA/Megatron-LM/commit/e82a8e7bd3a94cf7c4ec77d2cb86683a7b97d132
