### ISSUE TITLE
Using the environment variables for moe training will report an error --overlap-moe-expert-parallel-comm will report an error

### ISSUE THREAD

**Issue by leoda1** [NVIDIA/Megatron-LM#1862]
**Describe the bug**
Hi Megatron Dev team,
I have tested core_v0.15.0rc7, core_v0.15.0rc5, and the latest main branch, and all of them exhibit the same issue. I would really appreciate any insight into what might be causing this bug. 
Training runs normally when --overlap-moe-expert-parallel-comm is disabled. However, when I enable --overlap-moe-expert-parallel-comm, the training crashes with the following error:
```txt
[rank24]: Traceback (most recent call last):
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/pretrain_gpt.py", line 233, in <module>
[rank24]:     pretrain(
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/training/training.py", line 732, in pretrain
[rank24]:     iteration, num_floating_point_operations_so_far = train(
[rank24]:                                                       ^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/training/training.py", line 2244, in train
[rank24]:     ) = train_step(
[rank24]:         ^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/training/training.py", line 1252, in train_step
[rank24]:     losses_reduced = forward_backward_func(
[rank24]:                      ^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 1709, in forward_backward_pipelining_with_interleaving
[rank24]:     output_tensor, input_tensor_grad = forward_backward_helper_wrapper(
[rank24]:                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 1303, in forward_backward_helper_wrapper
[rank24]:     return combined_1f1b_schedule_for_interleaved_pipelining(
[rank24]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/combined_1f1b.py", line 199, in combined_1f1b_schedule_for_interleaved_pipelining
[rank24]:     output_tensor, num_tokens, input_tensor_grad = combined_forward_backward_step(
[rank24]:                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/combined_1f1b.py", line 392, in combined_forward_backward_step
[rank24]:     output_tensor = type(f_schedule_plan or b_schedule_plan).run(
[rank24]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/models/common/model_chunk_schedule_plan.py", line 449, in run
[rank24]:     f_input, b_grad = TransformerLayerSchedulePlan.run(
[rank24]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/models/common/model_chunk_schedule_plan.py", line 208, in run
[rank24]:     b_grad = b_layer.mlp.backward(b_grad)
[rank24]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/utils.py", line 212, in backward
[rank24]:     return self._backward(*output_grad)
[rank24]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/utils.py", line 225, in _backward
[rank24]:     output_grad = self.backward_func(outputs, output_grad)
[rank24]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/models/gpt/fine_grained_callables.py", line 33, in wrapped_func
[rank24]:     return method_ref()(*args, **kwarg)
[rank24]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/models/gpt/fine_grained_callables.py", line 277, in backward_impl
[rank24]:     self.default_backward_func(outputs + self.before_detached, grads)
[rank24]:   File "/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/Megatron-LM/megatron/core/pipeline_parallel/utils.py", line 155, in default_backward_func
[rank24]:     Variable._execution_engine.run_backward(
[rank24]:   File "/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py", line 307, in apply
[rank24]:     return user_fn(self, *args)
[rank24]:            ^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/module/linear.py", line 788, in backward
[rank24]:     wgrad, grad_bias_ = wgrad_gemm(inputmat_total, grad_output)
[rank24]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/module/linear.py", line 768, in wgrad_gemm
[rank24]:     dw, db, *_ = general_gemm(x, dy, **wgrad_gemm_kwargs)
[rank24]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]:   File "/usr/local/lib/python3.12/dist-packages/transformer_engine/pytorch/cpp_extensions/gemm.py", line 105, in general_gemm
[rank24]:     out, bias_grad, gelu_input, extra_output = tex.generic_gemm(*args, **kwargs)
[rank24]:                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank24]: RuntimeError: /workspace/TransformerEngine/transformer_engine/common/gemm/cublaslt_gemm.cu:92 in function CanonicalizeGemmInput: Assertion failed: A.has_data() || A.has_columnwise_data(). Input A does not hold any data!
[rank24]:[W1014 09:35:19.277693332 ProcessGroupNCCL.cpp:1505] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```
I did not make any code changes to Megatron, and used 4 nodes 32 h200 gpus with docker image ngc25.06. The configuration for mpirun and model configuration is as follows:
```shell
#! /bin/bash

TIMESTAMP=$(date +'%Y.%m.%d-%H:%M:%S')

NET_DEVICE="bond0"
MLP_GPU=8
MLP_MPI_HOSTFILE=$2
MLP_WORKER_0_PORT=29500
MLP_WORKER_NUM=$3
source $1

mkdir -p logs/${EXP_NAME}

mpirun -np $((MLP_WORKER_NUM * MLP_GPU)) \
        --hostfile ${MLP_MPI_HOSTFILE} \
        --allow-run-as-root   \
        --output-filename logs/${TIMESTAMP} \
        --mca oob_tcp_if_include ${NET_DEVICE} \
        -x NCCL_DEBUG=version \
        -x MASTER_ADDR=$(cat $MLP_MPI_HOSTFILE | head -n 1 | sed -s 's/slots=8//g') \
        -x MASTER_PORT=${MLP_WORKER_0_PORT} \
        -x GLOO_SOCKET_IFNAME=${NET_DEVICE} \
        -x NCCL_SOCKET_IFNAME=${NET_DEVICE} \
        -x LD_PRELOAD=/inspire/hdd/global_user/huxiaohe-p-huxiaohe/liuda/nccl/build/lib/libnccl.so.2 \
        -x LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nvshmem/12:$LD_LIBRARY_PATH \
        -x NCCL_IB_HCA=="mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1" \
        -x NCCL_IB_GID_INDEX=3 \
        -x NCCL_NVLS_ENABLE=0 \
        -x CUDA_DEVICE_MAX_CONNECTIONS=1 \
	python  ${script_path} ${gpt_options}    2>&1 | tee logs/${EXP_NAME}/output_${TIMESTAMP}.log
```

```shell
#!/bin/bash
EXP_NAME="moe"
script_path="pretrain_gpt.py"
gpt_options="
    --bf16 \
    --no-overlap-p2p-communication \
    --num-layers 32 \
    --hidden-size 4096 \
    --ffn-hidden-size 14336 \
    --seq-length 4096 \
    --group-query-attention \
    --num-query-groups 8 \
    --max-position-embeddings 32768 \
    --num-attention-heads 32 \
    --disable-bias-linear \
    --swiglu \
    --use-flash-attn \
    --transformer-impl transformer_engine \
    --untie-embeddings-and-output-weights \
    --position-embedding-type rope \
    --no-position-embedding \
    --normalization RMSNorm \
    --use-mcore-models \
    --rotary-base 1000000 \
    --no-masked-softmax-fusion \
    --manual-gc \
    --micro-batch-size 1 \
    --global-batch-size $((64 * PET_NNODES)) \
    --tensor-model-parallel-size 1 \
    --pipeline-model-parallel-size 4 \
    --use-distributed-optimizer \
    --recompute-granularity selective \
    --num-layers-per-virtual-pipeline-stage 2 \
    --sequence-parallel \
    --optimizer adam \
    --adam-beta1 0.9 \
    --adam-beta2 0.95 \
    --adam-eps 1e-8 \
    --lr 1e-4 \
    --min-lr 1.0e-5 \
    --lr-decay-style cosine \
    --train-iters 15 \
    --lr-decay-iters 9000 \
    --lr-warmup-fraction .01 \
    --clip-grad 1.0 \
    --weight-decay 1e-2 \
    --hidden-dropout 0.0 \
    --attention-dropout 0.0 \
    --initial-loss-scale 65536 \
    --data-path ./moe/wudao_mistralbpe_content_document \
    --tokenizer-type Llama2Tokenizer \
    --tokenizer-model ./moe/tokenizer.model \
    --split 949,50,1 \
    --log-interval 1 \
    --eval-iters 20 \
    --eval-interval 1000 \
    --save-interval 2500 \
    --log-throughput \
    --timing-log-level 0 \
    --log-timers-to-tensorboard \
    --log-memory-to-tensorboard \
    --distributed-timeout-minutes 60 \
    --init-method-std 0.01 \
    --moe-token-dispatcher-type alltoall \
    --expert-model-parallel-size 8 \
    --num-experts 8 \
    --moe-router-topk 2 \
    --moe-router-dtype=fp32 \
    --moe-router-load-balancing-type aux_loss \
    --moe-aux-loss-coeff 1e-2 \
    --overlap-param-gather \
    --overlap-grad-reduce \
    --overlap-moe-expert-parallel-comm \
"
```

**Comment by qi7kuo** [comment]
Hello, I also meet the problem. How to solve it? Thanks

**Comment by leoda1** [comment]
> Hello, I also meet the problem. How to solve it? Thanks

I found that when tp is greater than 1, it is normal. But I don’t know why.

**Comment by leoda1** [comment]
Hi @yashaswikarnati,
Could you please share the shell script and machine configuration that produced the result of [468 tflops training](https://docs.nvidia.com/megatron-core/developer-guide/latest/api-guide/moe.html#) here?
Alternatively, could you explain why it doesn’t work when setting tp=1?
Many thanks in advance for your help!

**Comment by yashaswikarnati** [comment]
Adding @lhb8125 for --overlap-moe-expert-parallel-comm

**Comment by yashaswikarnati** [comment]
@leoda1  Could you share which particular model configuration you were referring

**Comment by leoda1** [comment]
> [@leoda1](https://github.com/leoda1) Could you share which particular model configuration you were referring
This is the MoE training configuration for Mixtral 8x7B. I followed the Megatron-Core documentation and enabled the --overlap-moe-expert-parallel-comm option, but the performance is far below the expected 468 TFLOPS.
I’m also using 4 H200 nodes, but when --overlap-moe-expert-parallel-comm is enabled, TP=1 causes an error. Here is my training configuration，
```shell
#!/bin/bash
EXP_NAME="moe-group"
script_path="pretrain_gpt.py"

MODEL_ARGS="
    --use-mcore-models
    --disable-bias-linear
    --seq-length 4096
    --max-position-embeddings 32768
    --num-layers 32
    --hidden-size 4096
    --ffn-hidden-size 14336
    --num-attention-heads 32
    --init-method-std 0.01
    --attention-dropout 0.0
    --hidden-dropout 0.0
    --normalization RMSNorm
    --position-embedding-type rope
    --swiglu
    --untie-embeddings-and-output-weights
    --group-query-attention
    --num-query-groups 8
    --no-masked-softmax-fusion
    --no-position-embedding
    --rotary-base 1000000
"

MOE_ARGS="
    --num-experts 8
    --moe-router-topk 2
    --moe-router-load-balancing-type aux_loss
    --moe-aux-loss-coeff 1e-2
    --moe-token-dispatcher-type alltoall
    --overlap-param-gather
    --overlap-grad-reduce
    --overlap-moe-expert-parallel-comm
    --moe-grouped-gemm
    --delay-wgrad-compute
"

DATA_ARGS="
    --tokenizer-type Llama2Tokenizer \
    --tokenizer-model ./moe/tokenizer.model \
    --data-path ./moe/wudao_mistralbpe_content_document \
    --split 949,50,1 \
"

TRAINING_ARGS="
    --micro-batch-size 2 \
    --global-batch-size $((256 * PET_NNODES)) \
    --lr 1e-4 \
    --train-iters 2500 \
    --lr-decay-iters 320000 \
    --lr-decay-style cosine \
    --min-lr 1.0e-5 \
    --weight-decay 0.1 \
    --lr-warmup-iters 500 \
    --clip-grad 1.0 \
    --bf16 \
"

MODEL_PARALLEL_ARGS="
    --tensor-model-parallel-size 2 \
    --pipeline-model-parallel-size 4 \
    --expert-model-parallel-size 4 \
    --use-distributed-optimizer \
    --sequence-parallel \
    --num-layers-per-virtual-pipeline-stage 4 \
    --mtp-num-layers 1 \
"

LOGGING_ARGS="
    --log-interval 1 \
    --eval-iters 20000 \
    --eval-interval 10000 \
    --save-interval 10000 \
    --no-load-optim \
    --no-load-rng \
    --log-throughput \
    --timing-log-level 0 \
"
    # --distributed-timeout-minutes 60 \

gpt_options="
    ${MODEL_ARGS} \
    ${MODEL_PARALLEL_ARGS} \
    ${TRAIN_ARGS} \
    ${MOE_ARGS} \
    ${DATA_ARGS} \
    ${TRAINING_ARGS} \
    ${LOGGING_ARGS} \
"
```

**Comment by wujiahao15** [comment]
Hi @yashaswikarnati, I’ve also encountered this issue. I tested several model and runtime configurations and found that the problem only reproduces when `TP=1` and each GPU hosts exactly one expert.

<details open>
<summary>One configuration that reliably reproduces this issue is as follows:</summary>

```bash
#!/bin/bash
EXP_NAME="moe-group"
script_path="pretrain_gpt.py"

MODEL_ARGS="
    --use-mcore-models
    --disable-bias-linear
    --seq-length 4096
    --max-position-embeddings 32768
    --num-layers 16
    --hidden-size 4096
    --ffn-hidden-size 14336
    --num-attention-heads 32
    --init-method-std 0.01
    --attention-dropout 0.0
    --hidden-dropout 0.0
    --normalization RMSNorm
    --position-embedding-type rope
    --swiglu
    --untie-embeddings-and-output-weights
    --group-query-attention
    --num-query-groups 8
    --no-masked-softmax-fusion
    --no-position-embedding
    --rotary-base 1000000
"

MOE_ARGS="
    --num-experts 2
    --moe-router-topk 2
    --moe-router-force-load-balancing
    --moe-router-load-balancing-type aux_loss
    --moe-aux-loss-coeff 1e-2
    --moe-token-dispatcher-type alltoall
    --overlap-param-gather
    --overlap-grad-reduce
    --moe-grouped-gemm
    --overlap-moe-expert-parallel-comm
"

DATA_ARGS="
    --tokenizer-type Llama2Tokenizer \
    --tokenizer-model ./moe/tokenizer.model \
    --data-path ./moe/wudao_mistralbpe_content_document \
    --split 949,50,1 \
"

TRAINING_ARGS="
    --micro-batch-size 1 \
    --global-batch-size 32 \
    --lr 1e-4 \
    --train-iters 10 \
    --lr-decay-iters 320000 \
    --lr-decay-style cosine \
    --min-lr 1.0e-5 \
    --weight-decay 0.1 \
    --lr-warmup-iters 500 \
    --clip-grad 1.0 \
    --bf16 \
"

MODEL_PARALLEL_ARGS="
    --tensor-model-parallel-size 1 \
    --pipeline-model-parallel-size 4 \
    --expert-model-parallel-size 2 \
    --use-distributed-optimizer \
    --sequence-parallel \
    --num-layers-per-virtual-pipeline-stage 2 \
"

LOGGING_ARGS="
    --log-interval 1 \
    --eval-iters 0 \
    --eval-interval 10000 \
    --save-interval 10000 \
    --no-load-optim \
    --no-load-rng \
    --log-throughput \
    --timing-log-level 0 \
"

gpt_options="
    ${MODEL_ARGS} \
    ${MODEL_PARALLEL_ARGS} \
    ${TRAIN_ARGS} \
    ${MOE_ARGS} \
    ${DATA_ARGS} \
    ${TRAINING_ARGS} \
    ${LOGGING_ARGS} \
"
```
</details>

- Additional information
  - This model is Mixtral-7B while modifing `num_layers` from 32 to 16.
  - I run this training on a server with 8 H100 GPUs.

**Comment by lhb8125** [comment]
@wujiahao15 @leoda1 are you using the latest megatron dev branch and te branch?

**Comment by lhb8125** [comment]
@wujiahao15 @leoda1 I think I found the root cause of the bug but didn't have a good fix yet. When TP=1 and num_local_experts=1, the [dispatch_postprocess](https://github.com/NVIDIA/Megatron-LM/blob/dev/megatron/core/transformer/moe/token_dispatcher.py#L678) will return the input directly, which will be consumed in the following grouped gemm, so they cannot be released until the backward of groupedgemm. Previously, we captured the issue when num_local_experts=1 but missed the case of TP=1. Will figure out a formal fix later with @Wohox .

As a WAR, you could disable the free_input of mlp node in this case:
https://github.com/NVIDIA/Megatron-LM/blob/dev/megatron/core/models/gpt/fine_grained_callables.py#L66

**Comment by wujiahao15** [comment]
@lhb8125 Thanks for digging into this issue and identifying the root cause! I tried the workaround (disabling the MLP node by setting `mlp: False` in [this](https://github.com/NVIDIA/Megatron-LM/blob/dev/megatron/core/models/gpt/fine_grained_callables.py#L66)), and it works as expected.
