### ISSUE TITLE
Question about distribute training 

### ISSUE THREAD

**Issue by etoilestar** [NVIDIA/Megatron-LM#316]
hello, I just trained using pretrained_gpt_distribute.sh, but I meet Bus error: nonexistent physical address with signal 7,could you help me? hardware: rtx2080ti, docker:pytorch:22.03-py3, dataset:webtext

**Comment by etoilestar** [comment]
> elasped time to build and save shuffle-idx mapping (seconds): 0.064410
ceceb0c7f2e6:454:838 [0] NCCL INFO Using network Socket
ceceb0c7f2e6:455:839 [1] NCCL INFO Using network Socket
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
ceceb0c7f2e6:454:838 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff00,000fffff
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
ceceb0c7f2e6:455:839 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff00,000fffff
ceceb0c7f2e6:454:838 [0] NCCL INFO Channel 00/02 :    0   1
ceceb0c7f2e6:455:839 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
ceceb0c7f2e6:454:838 [0] NCCL INFO Channel 01/02 :    0   1
ceceb0c7f2e6:454:838 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
ceceb0c7f2e6:454:838 [0] NCCL INFO P2P is disabled between connected GPUs 0 and 1. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:454:838 [0] NCCL INFO Could not enable P2P between dev 0(=1b000) and dev 1(=1c000)
[ceceb0c7f2e6:454  :0:838] Caught signal 7 (Bus error: nonexistent physical address)
ceceb0c7f2e6:455:839 [1] NCCL INFO P2P is disabled between connected GPUs 1 and 0. You can repress this message with NCCL_IGNORE_DISABLED_P2P=1.
ceceb0c7f2e6:455:839 [1] NCCL INFO Could not enable P2P between dev 1(=1c000) and dev 0(=1b000)
[ceceb0c7f2e6:455  :0:839] Caught signal 7 (Bus error: nonexistent physical address)
==== backtrace (tid:    839) ====
 0 0x0000000000043090 killpg()  ???:0
 1 0x000000000018bb41 __nss_database_lookup()  ???:0
 2 0x000000000007587d ncclGroupEnd()  ???:0
 3 0x000000000007b0ef ncclGroupEnd()  ???:0
 4 0x0000000000059e97 ncclGetUniqueId()  ???:0
 5 0x00000000000489b1 ???()  /usr/lib/x86_64-linux-gnu/libnccl.so.2:0
 6 0x000000000004a655 ???()  /usr/lib/x86_64-linux-gnu/libnccl.so.2:0
 7 0x0000000000063dcc ncclRedOpDestroy()  ???:0
 8 0x0000000000008609 start_thread()  ???:0
 9 0x000000000011f133 clone()  ???:0
=================================
==== backtrace (tid:    838) ====
 0 0x0000000000043090 killpg()  ???:0
 1 0x000000000018bb41 __nss_database_lookup()  ???:0
 2 0x000000000007587d ncclGroupEnd()  ???:0
 3 0x000000000007b0ef ncclGroupEnd()  ???:0
 4 0x0000000000059e97 ncclGetUniqueId()  ???:0
 5 0x00000000000489b1 ???()  /usr/lib/x86_64-linux-gnu/libnccl.so.2:0
 6 0x000000000004a655 ???()  /usr/lib/x86_64-linux-gnu/libnccl.so.2:0
 7 0x0000000000063dcc ncclRedOpDestroy()  ???:0
 8 0x0000000000008609 start_thread()  ???:0
 9 0x000000000011f133 clone()  ???:0
=================================
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 454) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
===================================================
pretrain_gpt.py FAILED
---------------------------------------------------
Failures:
[1]:
  time      : 2023-04-21_07:42:43
  host      : ceceb0c7f2e6
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 455)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 455
---------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-21_07:42:43
  host      : ceceb0c7f2e6
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 454)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 454
===================================================

**Comment by YaboSun** [comment]
I resolved this issue in my Docker environment by increasing the shm-size.

**Comment by etoilestar** [comment]
thank you， this issue has been solved in this way, so I can train now.

**Comment by BoxiangW** [comment]
Change of shm-size solved mine as well, but why it works like this?
