### ISSUE TITLE
Distributed optimizer DP-independent checkpoint would use redundant gpu memory.

### ISSUE THREAD

**Issue by cicirori** [NVIDIA/Megatron-LM#380]
When reducing the training size, use dp-independent checkpoint would cause gpu oom sometimes.
```
Traceback (most recent call last):
  File "megatron-lm/pretrain_gpt.py", line 116, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "megatron-lm/megatron/training.py", line 113, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "megatron-lm/megatron/training.py", line 527, in setup_model_and_optimizer
    args.iteration = load_checkpoint(model, optimizer, opt_param_scheduler)
  File "megatron-lm/megatron/checkpointing.py", line 572, in load_checkpoint
    optimizer.load_state_dict(state_dict['optimizer'])
  File "megatron-lm/megatron/optimizer/distrib_optimizer.py", line 563, in load_state_dict
    self.optimizer.load_state_dict({
  File "/opt/conda/lib/python3.10/site-packages/torch/optim/optimizer.py", line 379, in load_state_dict
    state_dict = deepcopy(state_dict)
  File "/opt/conda/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/conda/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 118, in __deepcopy__
    new_storage = self._typed_storage()._deepcopy(memo)
  File "/opt/conda/lib/python3.10/site-packages/torch/storage.py", line 661, in _deepcopy
    return self._new_wrapped_storage(copy.deepcopy(self._untyped_storage, memo))
  File "/opt/conda/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/opt/conda/lib/python3.10/site-packages/torch/storage.py", line 98, in __deepcopy__
    new_storage = self.clone()
  File "/opt/conda/lib/python3.10/site-packages/torch/storage.py", line 112, in clone
    return type(self)(self.nbytes(), device=self.device).copy_(self)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 170.00 MiB (GPU 1; 79.35 GiB total capacity; 77.59 GiB already allocated; 7.19 MiB free; 77.99 GiB reserved in total by PyTorch) If reserved memory is >> al
located memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by cicirori** [comment]
https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/optimizer/distrib_optimizer.py#L540
the optimizer's `load_state_dict` of torch will deep copy it's inputs.

just tried change `init_shard` from cuda device to cpu, this problem seems fixed.

@lmcafee-nvidia
