### ISSUE TITLE
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:839, unhandled system error, NCCL version 2.8.3

### ISSUE THREAD

**Issue by JinliangLu96** [NVIDIA/Megatron-LM#71]
I am trying to pretrained gpt on two gpus, but I got the following error.

```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
using world size: 2, data-parallel-size: 2, tensor-model-parallel size: 1, pipeline-model-parallel size: 1 
using torch.float16 for parameters ...
------------------------ arguments ------------------------
  adam_beta1 ...................................... 0.9
  adam_beta2 ...................................... 0.999
  adam_eps ........................................ 1e-08
  adlr_autoresume ................................. False
  adlr_autoresume_interval ........................ 1000
  apply_query_key_layer_scaling ................... True
  apply_residual_connection_post_layernorm ........ False
  attention_dropout ............................... 0.1
  attention_softmax_in_fp32 ....................... False
  bert_load ....................................... None
  bias_dropout_fusion ............................. True
  bias_gelu_fusion ................................ True
  block_data_path ................................. None
  checkpoint_activations .......................... True
  checkpoint_num_layers ........................... 1
  clip_grad ....................................... 1.0
  consumed_train_samples .......................... 0
  consumed_valid_samples .......................... 0
  data_impl ....................................... mmap
  data_parallel_size .............................. 2
  data_path ....................................... ['gpt-megatron/chinese-gpt_text_document']
  DDP_impl ........................................ local
  distribute_checkpointed_activations ............. False
  distributed_backend ............................. nccl
  eod_mask_loss ................................... False
  eval_interval ................................... 1000
  eval_iters ...................................... 10
  exit_duration_in_mins ........................... None
  exit_interval ................................... None
  faiss_use_gpu ................................... False
  finetune ........................................ False
  fp16 ............................................ True
  fp16_lm_cross_entropy ........................... False
  fp32_allreduce .................................. False
  fp32_residual_connection ........................ False
  global_batch_size ............................... 64
  hidden_dropout .................................. 0.1
  hidden_size ..................................... 1024
  hysteresis ...................................... 2
  ict_head_size ................................... None
  ict_load ........................................ None
  indexer_batch_size .............................. 128
  indexer_log_interval ............................ 1000
  init_method_std ................................. 0.02
  initial_loss_scale .............................. 4294967296
  layernorm_epsilon ............................... 1e-05
  lazy_mpu_init ................................... None
  load ............................................ gpt-models/
  local_rank ...................................... 0
  log_interval .................................... 100
  loss_scale ...................................... None
  loss_scale_window ............................... 1000
  lr .............................................. 0.00015
  lr_decay_iters .................................. 320000
  lr_decay_samples ................................ None
  lr_decay_style .................................. cosine
  lr_warmup_fraction .............................. 0.01
  lr_warmup_iters ................................. 0
  lr_warmup_samples ............................... 0
  make_vocab_size_divisible_by .................... 128
  mask_prob ....................................... 0.15
  max_position_embeddings ......................... 1024
  merge_file ...................................... gpt2-merges.txt
  micro_batch_size ................................ 8
  min_loss_scale .................................. 1.0
  min_lr .......................................... 1e-05
  mmap_warmup ..................................... False
  no_load_optim ................................... False
  no_load_rng ..................................... False
  no_save_optim ................................... False
  no_save_rng ..................................... False
  num_attention_heads ............................. 16
  num_layers ...................................... 12
  num_workers ..................................... 2
  onnx_safe ....................................... None
  openai_gelu ..................................... False
  override_lr_scheduler ........................... False
  params_dtype .................................... torch.float16
  pipeline_model_parallel_size .................... 1
  query_in_block_prob ............................. 0.1
  rampup_batch_size ............................... None
  rank ............................................ 0
  report_topk_accuracies .......................... []
  reset_attention_mask ............................ False
  reset_position_ids .............................. False
  save ............................................ gpt-models/
  save_interval ................................... 10000
  scaled_masked_softmax_fusion .................... True
  scaled_upper_triang_masked_softmax_fusion ....... True
  seed ............................................ 1234
  seq_length ...................................... 1024
  short_seq_prob .................................. 0.1
  split ........................................... 949,50,1
  tensor_model_parallel_size ...................... 1
  tensorboard_dir ................................. None
  titles_data_path ................................ None
  tokenizer_type .................................. GPT2BPETokenizer
  train_iters ..................................... 500000
  train_samples ................................... None
  use_checkpoint_lr_scheduler ..................... False
  use_cpu_initialization .......................... False
  use_one_sent_docs ............................... False
  vocab_file ...................................... gpt2-vocab.json
  weight_decay .................................... 0.01
  world_size ...................................... 2
-------------------- end of arguments ---------------------
setting number of micro-batches to constant 4
> building GPT2BPETokenizer tokenizer ...
 > padded vocab (size: 30000) with 80 dummy tokens (new size: 30080)
> initializing torch distributed ...
> initializing tensor model parallel with size 1
> initializing pipeline model parallel with size 1
> setting random seeds to 1234 ...
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
time to initialize megatron (seconds): 44.130
[after megatron is initialized] datetime: 2021-02-24 07:41:32 
building GPT model ...
 > number of parameters on (tensor, pipeline) model parallel rank (0, 0): 183007232
> learning rate decay style: cosine
WARNING: could not find the metadata file gpt-models/latest_checkpointed_iteration.txt 
    will not load any checkpoints and will start from random
time (ms) | load checkpoint: 0.21
[after model, optimizer, and learning rate scheduler are built] datetime: 2021-02-24 07:41:32 
> building train, validation, and test datasets ...
 > datasets target sizes (minimum size):
    train:      32000000
    validation: 320640
    test:       640
> building train, validation, and test datasets for GPT ...
 > building dataset index ...
    reading sizes...
    reading pointers...
    reading document index...
    creating numpy buffer of mmap...
    creating memory view of numpy buffer...
 > finished creating indexed dataset in 0.000936 seconds
    number of documents: 100000
 > dataset split:
    train:
     document indices in [0, 94900) total of 94900 documents
    validation:
     document indices in [94900, 99900) total of 5000 documents
    test:
     document indices in [99900, 100000) total of 100 documents
Traceback (most recent call last):
  File "pretrain_gpt.py", line 146, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-LM/megatron/training.py", line 115, in pretrain
    = build_train_valid_test_data_iterators(
  File "/workspace/Megatron-LM/megatron/training.py", line 993, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "pretrain_gpt.py", line 131, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 38, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 116, in _build_train_valid_test_datasets
    train_dataset = build_dataset(0, 'train')
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 110, in build_dataset
    dataset = GPTDataset(name, data_prefix,
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 152, in __init__
    self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 300, in _build_index_mappings
    torch.distributed.all_reduce(counts, group=mpu.get_data_parallel_group())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:839, unhandled system error, NCCL version 2.8.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Traceback (most recent call last):
  File "pretrain_gpt.py", line 146, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider, forward_step,
  File "/workspace/Megatron-LM/megatron/training.py", line 115, in pretrain
    = build_train_valid_test_data_iterators(
  File "/workspace/Megatron-LM/megatron/training.py", line 993, in build_train_valid_test_data_iterators
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets_provider(
  File "pretrain_gpt.py", line 131, in train_valid_test_datasets_provider
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 38, in build_train_valid_test_datasets
    return _build_train_valid_test_datasets(data_prefix[0],
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 116, in _build_train_valid_test_datasets
    train_dataset = build_dataset(0, 'train')
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 110, in build_dataset
    dataset = GPTDataset(name, data_prefix,
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 152, in __init__
    self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
  File "/workspace/Megatron-LM/megatron/data/gpt_dataset.py", line 300, in _build_index_mappings
    torch.distributed.all_reduce(counts, group=mpu.get_data_parallel_group())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1107, in all_reduce
    work = group.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:839, unhandled system error, NCCL version 2.8.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 303, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launch.py", line 294, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'pretrain_gpt.py', '--local_rank=1', '--num-layers', '12', '--hidden-size', '1024', '--num-attention-heads', '16', '--micro-batch-size', '8', '--global-batch-size', '64', '--seq-length', '1024', '--max-position-embeddings', '1024', '--train-iters', '500000', '--lr-decay-iters', '320000', '--save', 'gpt-models/', '--load', 'gpt-models/', '--data-path', 'gpt-megatron/chinese-gpt_text_document', '--vocab-file', 'gpt2-vocab.json', '--merge-file', 'gpt2-merges.txt', '--data-impl', 'mmap', '--split', '949,50,1', '--distributed-backend', 'nccl', '--lr', '0.00015', '--lr-decay-style', 'cosine', '--min-lr', '1.0e-5', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--lr-warmup-fraction', '.01', '--checkpoint-activations', '--log-interval', '100', '--save-interval', '10000', '--eval-interval', '1000', '--eval-iters', '10', '--fp16']' returned non-zero exit status 1.

```
I use the NGC's recent PyTorch containers version 20.12, and the script was running in the docker container. So, I don't know why the nccl error occurs.

When I used 1 gpu, it works well. But running multi-gpus will fails. I don't know how to solve it. Can someone help me? Thank you.

**Comment by JinliangLu96** [comment]
I have fixed the problem. It caused by the size of 'dev/shm' in the docker container. I used the following command to increase the size. And it works well.

```
docker run -it --gpus all --shm-size=1024m xxxx /bin/bash
```
